#app
server:
  port: 9104

spring:
  profiles:
    active: dev

# mybatis-plus相关配置
mybatis-plus:
   # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.wp.modules.*
  # 扫描枚举类 # 支持统配符 * 或者 ; 分割
  type-enums-package: com.wp.modules.*
  # 以下配置均有默认值,可以不设置
  global-config: 
    db-config: 
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: not-null
      #数据库类型
      db-type: mysql

